Add survey service deployment pipeline
ONSdigital/ras-deploy pull request #109
Opened 2019-05-17 10:39 UTC by gavinleeedwards

# Motivation and Context
Add deployment pipeline for to deploy survey service via Concourse

# What has changed
New survey service pipeline

# How to test?
Fly the pipeline with the pipeline secrets.  Create a new release.  If the pre-production box is ticked then the release will be deployed to prepared.  To deploy to prod, untick the box and run the pipeline again.

2019-05-20 15:36 UTC, necrophonic commented
Added new PR which updates this branch to work with updated `rm-survey-service` code: https://github.com/ONSdigital/ras-deploy/pull/110.

2019-05-20 15:37 UTC, necrophonic requested changes
Looks good - should merge in PR https://github.com/ONSdigital/ras-deploy/pull/110 for dealing with new `rm-survey-service` code

2019-06-13 12:54 UTC, ChristopherMShelton approved these changes

2019-07-03 12:07 UTC, necrophonic commented on pipelines/deployment.yml
> +          - name: survey-service
Do the preprod and prod jobs need to exist here are the "real" ones are separate jobs now (in `pipelines/survey-service.yml `)?

2019-07-03 12:07 UTC, necrophonic commented on pipelines/deployment.yml
> +      manifest: survey-service/manifest.yml
Not sure if we need these jobs (as in previous comment) but these manifests would be wrong I think as there are specific manifests for preprod and prod

2019-07-03 15:42 UTC, gavinleeedwards commented
I've now removed all of the preprod and prod jobs that were disabled and reflown the pipeline, so the `deployment.yml` is now around half of the size it was.  It looks as though disabled jobs are ignored anyway so it's made no difference to the pipeline, which is good.

2019-07-04 10:07 UTC, necrophonic approved these changes

2019-07-04 12:33 UTC, merged