Remove backstage from the pipelines
ONSdigital/ras-deploy pull request #31
Opened 2018-06-28 15:55 UTC by jcox-dev

# Motivation and Context
The [response-operations-ui](https://github.com/ONSdigital/response-operations-ui/) service will no longer be proxying its requests through backstage. This PR removes any mention of the service from the pipelines and secrets.

# What has changed

Removed all mention of backstage service.

# How to test?

Fly this branch's pipeline configuration and check the acceptance tests pass and the response-operations service can be accessed and used without issue.

# Links

- [Trello](https://trello.com/c/0lPdzRbt)
- [Remove from docker PR](https://github.com/ONSdigital/ras-rm-docker-dev/pull/64)
- [Remove config PR](https://github.com/ONSdigital/response-operations-ui/pull/199)

2018-06-28 15:59 UTC, jcox-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [TBL: response-operations-ui should directly call other services (not via backstage)](https://trello.com/c/0lPdzRbt/144-tbl-response-operations-ui-should-directly-call-other-services-not-via-backstage)

2018-07-02 08:23 UTC, benjefferies requested changes
Looks good. Similar changes need to occur in https://github.com/ONSdigital/ras-deploy/blob/master/pipelines/loadtest.yml

2018-07-02 11:59 UTC, jcox-dev commented
@benjefferies [should already be in](https://github.com/ONSdigital/ras-deploy/pull/31/files#diff-768f93084be02d1cb6a6d85767606579) on this branch.

2018-07-02 12:06 UTC, benjefferies approved these changes

2018-07-03 08:07 UTC, liamtoozer approved these changes

2018-07-03 08:48 UTC, merged