Create respondent-home-ui pipeline
ONSdigital/ras-deploy pull request #34
Opened 2018-07-13 10:34 UTC by benjefferies

# Motivation and Context
Creating new pipeline for respondent home ui. All functional testing is
carried out in the integration tests so we don't need a set of
acceptance tests in the pipeline. We will want a smoke test at some
point at the variable stages of the pipeline.

# What has changed
Add respondent-home-ui pipeline to deploy to latest, fake pre-prod and fake prod

# How to test?
1. Go to http://respondent-home-ui-latest.apps.devtest.onsclofo.uk/
2. Enter a valid enrolment code
3. Check to see redirected

# Links
https://trello.com/c/YHoxwSCv/166-url-link-to-access-social-test-1-survey-5

2018-07-13 12:03 UTC, tomphp approved these changes
Looks good as a first step.

2018-07-16 08:44 UTC, jcox-dev requested changes

2018-07-16 08:44 UTC, jcox-dev commented on pipelines/respondent-home-ui.yml
> +        EQ_URL: https://staging-new-surveys.dev.eq.ons.digital/
Can we get the default `EQ_URL` entries to point at `[host]/session?token=` [as found in runner](https://github.com/ONSdigital/eq-survey-runner/blob/755681b6f4840df7d1430ea9ad2636b0275253b9/app/views/session.py#L38) so we can append the JWT to the string without hardcoding any paths/params in RH code.

2018-07-16 09:34 UTC, jcox-dev approved these changes

2018-07-16 14:48 UTC, merged

2018-07-16 15:33 UTC, jcox-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dev task 7: EXT: Access eQ social survey (RH) (???)](https://trello.com/c/SwkUMf9O/99-dev-task-7-ext-access-eq-social-survey-rh)