Loadtest pipeline
ONSdigital/ras-deploy pull request #39
Opened 2018-07-18 14:48 UTC by mfcrocker

# Motivation and Context
We're building a load test, but the rebases are getting painful with the long running feature branch

# What has changed
YAML!
- Parameterising values
- Add groups  and teardown job
- Add GOV.UK Notify mock
- Simplify load test job naming

# How to test?
It's deployed to the `loadtestwip` pipeline

2018-07-19 12:00 UTC, benjefferies approved these changes

2018-07-20 09:26 UTC, PurpleBooth approved these changes

2018-07-20 09:26 UTC, PurpleBooth requested changes

2018-07-20 09:26 UTC, PurpleBooth commented on scripts/loadtest-scripts/prepare_loadtests.py
> +    # enrolment_codes = create_enrolment_codes(1)
Commented out code?!

2018-07-20 11:04 UTC, PurpleBooth approved these changes

2018-07-20 11:06 UTC, merged