Script refactoring
ONSdigital/ras-deploy pull request #45
Opened 2018-07-24 09:58 UTC by mfcrocker

# Motivation and Context
Continues work to move this from a quick and dirty script to something more maintainable

# What has changed
Extracting methods into classes, use of logging

# How to test?
Spin up docker-dev, make sure you've got all the right ENV vars set and run the script. Alternatively, modify and fly the loadtest.yml pipeline with the branch (the sit space on devtest is set up with this already)

2018-07-24 10:05 UTC, mfcrocker commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automate preparation of a load testing space](https://trello.com/c/AHs4Uq3C/41-automate-preparation-of-a-load-testing-space)

2018-07-24 12:57 UTC, tomphp requested changes
In order to make these messages appear we need to decrease the log level. i.e.

`logging.getLogger().setLevel(logging.DEBUG)`

2018-07-24 15:17 UTC, tomphp approved these changes
Have run and is outputting message as expected.

2018-07-25 08:38 UTC, PurpleBooth approved these changes

2018-07-25 09:26 UTC, merged