Sdc responses dashboard pipeline
ONSdigital/ras-deploy pull request #72
Opened 2018-08-31 12:02 UTC by AdamHawtin

# Motivation and Context

The sdc-responses-dashboard app needs a pipeline to deploy

# What has changed

- Added a pipeline for the sdc-responses-dashboard app, currently only to ci-latest space in devtest

# How to test?

This pipeline has already been flown, look at the responses-dashboard pipeline in concourse to see it.

# Links

https://trello.com/c/HTFhcfvs/63-create-concourse-pipeline-to-devtest#

2018-08-31 12:03 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create concourse pipeline to devtest](https://trello.com/c/HTFhcfvs/63-create-concourse-pipeline-to-devtest)

2018-08-31 12:54 UTC, liamtoozer submitted a review, later dismissed
Looks good 👍 There's no notification for deployment failure, is that intentional?

2018-08-31 14:27 UTC, liamtoozer submitted a review, later dismissed
Nice 👍

2018-11-09 15:24 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Extend concourse pipeline to Prod](https://trello.com/c/GCy8zER6/65-extend-concourse-pipeline-to-prod)

2018-11-16 10:07 UTC, liamtoozer approved these changes

2018-11-16 11:32 UTC, davidmort requested changes

2018-11-16 11:32 UTC, davidmort commented on pipelines/sdc-responses-dashboard.yml
> +  - task: run-unit-tests
not sure we need to run the unit tests on a deploy into every env, if the unit tests have run and passed in the devtest deploy stage of the pipeline then wouldn't be enough?

2018-11-16 12:12 UTC, davidmort approved these changes

2018-11-16 14:09 UTC, merged