Add environment variables.
ONSdigital/ras-deploy pull request #8
Opened 2018-05-22 08:48 UTC by rjweeks

This ticket involved changing the Sample Service for detecting duplicate sample_refs in sample uploads.
We also moved the backstage endpoint functionality to Response Operations UI.

New pattern for variables is like: SAMPLE_URL and not RM_SAMPLE_SERVICE_URL

The RM_SAMPLE_SERVICE_URL variants should be removed when ras-backstage is retired.

2018-05-22 09:50 UTC, liamtoozer approved these changes

2018-05-22 09:51 UTC, jcox-dev approved these changes

2018-05-22 09:54 UTC, benjefferies requested changes

2018-05-22 09:54 UTC, benjefferies commented on concourse/pipeline.yml
> +      SAMPLE_HOST: rm-sample-service-ci.apps.devtest.onsclofo.uk
Should we not be adding SAMPLE_URL? https://github.com/ONSdigital/response-operations-ui/pull/160/files#diff-fdf313ed2303059c44a9ebfffbef8eebR47

2018-05-25 13:42 UTC, benjefferies approved these changes

2018-05-25 13:42 UTC, merged