Add attempts to RH smoke tests
ONSdigital/ras-deploy pull request #80
Opened 2018-10-01 13:25 UTC by liamtoozer

# Motivation and Context

A pipeline job failed for respondent-home-ui during a smoke test on `GET /info` for one of the dependent services. This might have been caused by an intermittent platform error, although it was difficult to tell from the logs.

If the smoke test fails, Concourse will now attempt re-run the smoke test 4 times after the first failure. 

# What has changed

`respondent-home-ui.yml`

2018-10-02 07:49 UTC, emilioward approved these changes

2018-10-02 09:50 UTC, AdamHawtin requested changes
It seems wrong to me to re-attempt the whole test run because of transient connection errors, I think the individual requests should be retried appropriately rather than the entire test run.

2018-10-02 12:40 UTC, liamtoozer commented
That's a good shout @AdamHawtin. We could use something like this instead maybe? Might be good to discuss with the team

https://github.com/onsdigital/rasrm-acceptance-tests/blob/c91f151f8fe812674d906021077218fafeee36ee/acceptance_tests/__init__.py#L20

2018-10-05 14:06 UTC, liamtoozer commented
Will raise a tech debt card to cover work from comments.

2018-10-05 14:06 UTC, closed without merging