edit config for UAA and response operations
ONSdigital/ras-deploy pull request #9
Opened 2018-05-23 10:16 UTC by tej99

Config update for: https://github.com/ONSdigital/response-operations-ui/pull/163

Response operations should directly sign in with UAA.

https://trello.com/c/oodNbXR2/100-response-operations-ui-should-sign-in-directly-using-uaa-not-via-backstage

2018-05-23 14:48 UTC, gavinleeedwards requested changes
In the 4 ras-backstage-*-deploy jobs, they're still set up to use the 'ras-backstage' client which is no longer being created and has been removed from the secrets file.

2018-05-24 07:09 UTC, tej99 commented
@gavinleeedwards Made the change, it will now temporally use the response operations UAA client since backstage it eventually going to be removed.

2018-05-24 08:05 UTC, tej99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [response-operations-ui should sign in directly using uaa (not via backstage)](https://trello.com/c/oodNbXR2/100-response-operations-ui-should-sign-in-directly-using-uaa-not-via-backstage)

2018-05-24 08:16 UTC, gavinleeedwards approved these changes
Looks good.  Once this is merged, you'll need to update the secrets file and re-deploy the pipeline - Ben posted a link on Slack with instructions but let me know if you need a hand.

2018-05-24 08:30 UTC, benjefferies requested changes
@tej99 can you update the secrets file

2018-05-31 16:53 UTC, benjefferies commented
@tej99 we've put the secrets file encrypted in sharepoint under ras -> ras pipeline. You should be able to download it, update it, upload it. If you have a lastpass account I can share you the password for the encrypted secrets file

2018-06-01 08:45 UTC, benjefferies approved these changes

2018-06-01 08:45 UTC, merged