Add load test task to RH pipeline
ONSdigital/ras-deploy pull request #95
Opened 2018-10-31 15:09 UTC by jcox-dev

2018-10-31 15:19 UTC, jcox-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [SUS039 Run Performance test for RH in Concourse](https://trello.com/c/0tE6f10z/227-sus039-run-performance-test-for-rh-in-concourse)

2018-11-20 13:34 UTC, davidmort requested changes

2018-11-20 13:34 UTC, davidmort commented on pipelines/respondent-home-ui.yml
> +  - task: load-tests
don't think we should be running load tests in preprod/prod as part of the deployment pipeline, feels like something that will be done is envs before the preprod stage

2019-02-08 16:24 UTC, NickGrantONS commented
I think we should close this PR, because I agree that it's probably the wrong place to do load testing - we need to think about how we're going to do our automated load/performance testing, which will probably be done in a totally different environment

2019-02-11 14:05 UTC, closed without merging